version: '3.8'
services:
  values_db:
    image: tarantool/tarantool:latest
    hostname: values_db
    ports:
      - "3301:3301"
    environment:
      - TARANTOOL_MEMORY_GB=1.0
    volumes:
      - ./migrations/value_store/:/opt/tarantool/
    healthcheck:
        test: ["CMD-SHELL", "cat /etc/OK"]
        interval: 30s
        timeout: 10s
        retries: 20
    command: touch /etc/OK && tarantool /opt/tarantool/init.lua
  api:
    build: .
    hostname: api
    ports:
      - 8081:8081
    environment:
      - DOCKER_CONFIG_PATH=config/config.toml
    depends_on:
      values_db:
        condition: service_healthy

