[server]
  port = ":8081"
  log_level = "debug"
  token_ttl = "1h"

[value_database]
  user = "postgres"
  password = "postgres"
  host = "values_db"
  db_name = "filmoteka"
  port = ":3301"

[user_database]
  user = "postgres"
  password = "postgres"
  host = "values_db"
  db_name = "filmoteka"
  port = ":3301"
  