[server]
  port = ":8081"
  log_level = "debug"
  token_ttl = "1h"

[value_database]
  host = "values_db"
  port = ":3301"

[user_database]
  def_user="admin"
  def_passwd="presale"
  host = "udb"
  port = ":3302"
  